services:
  - type: web
    name: social-media-ai-content
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    repo: https://github.com/Karehmaciu/Social-Media-AI-Content.git
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: TINYMCE_API_KEY
        sync: false
